import { Metadata } from "next";
import dynamic from "next/dynamic";
import { Suspense } from "react";
import { Sparkles, Zap, Gift, Star } from "lucide-react";
import { generateSEOMetadata } from "@/components/SEO";
import {
  BreadcrumbStructuredData,
  WebApplicationStructuredData,
} from "@/components/StructuredData";
import { FAQStructuredData } from "@/components/FAQStructuredData";
import { FortuneCookieStatic } from "@/components/FortuneCookieStatic";
import { DeferredMount } from "@/components/DeferredMount";

// Dynamic import for interactive layer
const FortuneCookieInteractive = dynamic(
  () =>
    import("@/components/FortuneCookieInteractive").then(
      (mod) => mod.FortuneCookieInteractive,
    ),
  { ssr: false, loading: () => null },
);

// Static generation with revalidation
export const revalidate = 86400; // 24 hours

export const metadata: Metadata = generateSEOMetadata({
  title: "Free Online Fortune Cookie - Open Your Fortune Now | No Signup",
  description:
    "Get your free fortune cookie online instantly! AI-powered fortune messages with lucky numbers. No signup, no download — just click and discover your fortune. 500+ unique messages.",
  url: "/free-online-fortune-cookie",
  type: "website",
});

const faqs = [
  {
    question: "Can I get a fortune cookie online for free?",
    answer:
      "Yes! Our free online fortune cookie generator lets you crack open virtual fortune cookies instantly. No signup, no download, no cost — just pure fortune fun!",
  },
  {
    question: "How many free fortune cookies can I get per day?",
    answer:
      "You can open up to 5 free fortune cookies per day as a guest. Sign in with Google to unlock 20 daily fortunes for free!",
  },
  {
    question: "Do I need to download anything to use the fortune cookie?",
    answer:
      "No download required! Our fortune cookie generator works directly in your web browser on any device — desktop, tablet, or mobile.",
  },
  {
    question: "Are the fortune cookie messages unique?",
    answer:
      "Yes! Each fortune is generated by AI in real-time, so every message is unique and personalized. We also have a library of 500+ curated fortune messages.",
  },
];

const benefits = [
  {
    icon: Zap,
    title: "Instant Results",
    description: "Click and get your fortune in seconds — no waiting!",
    gradient: "from-amber-500 to-orange-500",
  },
  {
    icon: Gift,
    title: "100% Free",
    description: "No signup, no credit card, no hidden fees.",
    gradient: "from-emerald-500 to-teal-500",
  },
  {
    icon: Sparkles,
    title: "AI-Powered",
    description: "Each fortune is uniquely generated by advanced AI.",
    gradient: "from-indigo-500 to-purple-500",
  },
  {
    icon: Star,
    title: "Lucky Numbers",
    description: "Every fortune comes with your personal lucky numbers.",
    gradient: "from-pink-500 to-rose-500",
  },
];

export default function FreeOnlineFortuneCookiePage() {
  return (
    <>
      <BreadcrumbStructuredData
        items={[
          { name: "Home", url: "/" },
          {
            name: "Free Online Fortune Cookie",
            url: "/free-online-fortune-cookie",
          },
        ]}
      />
      <WebApplicationStructuredData />
      <FAQStructuredData faqs={faqs} />

      <main className="min-h-screen w-full overflow-x-hidden relative bg-gradient-to-b from-amber-50/50 via-white to-orange-50/30">
        {/* Hero Section with Fortune Cookie */}
        <section className="relative z-10 pt-8 pb-12">
          <div className="container mx-auto px-4 text-center mb-8">
            <h1 className="text-3xl md:text-5xl font-heading font-bold text-slate-800 mb-4">
              Free Online Fortune Cookie
            </h1>
            <p className="text-lg md:text-xl text-slate-600 max-w-2xl mx-auto mb-2">
              Crack open a virtual fortune cookie and discover your personalized
              message — completely free, no signup needed!
            </p>
          </div>

          {/* Fortune Cookie - Static + Interactive */}
          <div className="relative z-10">
            <FortuneCookieStatic />
            <Suspense fallback={null}>
              <DeferredMount delay={2000} useIdle={false}>
                <FortuneCookieInteractive />
              </DeferredMount>
            </Suspense>
          </div>
        </section>

        {/* Benefits Section */}
        <section className="relative z-10 py-16 bg-white/80 backdrop-blur-sm border-y border-amber-100/50">
          <div className="container mx-auto px-4">
            <h2 className="text-2xl md:text-3xl font-heading font-bold text-center text-slate-800 mb-12">
              Why Choose Our Free Fortune Cookie Generator?
            </h2>
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-5xl mx-auto">
              {benefits.map((benefit) => {
                const Icon = benefit.icon;
                return (
                  <div
                    key={benefit.title}
                    className="text-center p-6 rounded-2xl bg-white border border-slate-100 shadow-sm hover:shadow-md transition-shadow"
                  >
                    <div
                      className={`w-14 h-14 mx-auto mb-4 rounded-xl bg-gradient-to-br ${benefit.gradient} flex items-center justify-center shadow-lg`}
                    >
                      <Icon className="w-7 h-7 text-white" aria-hidden="true" />
                    </div>
                    <h3 className="font-semibold text-slate-800 mb-2">
                      {benefit.title}
                    </h3>
                    <p className="text-sm text-slate-600">
                      {benefit.description}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* SEO Content Section */}
        <section className="relative z-10 py-16">
          <div className="container mx-auto px-4 max-w-4xl">
            <div className="grid md:grid-cols-2 gap-12">
              <div>
                <h2 className="text-2xl font-heading font-semibold text-slate-800 mb-4">
                  Get Your Free Fortune Cookie Online
                </h2>
                <p className="text-slate-600 mb-4 leading-relaxed">
                  Looking for a free fortune cookie online? You&apos;ve come to
                  the right place! Our AI-powered fortune cookie generator
                  creates unique, personalized messages just for you. Simply
                  click on the cookie above to crack it open and reveal your
                  fortune.
                </p>
                <p className="text-slate-600 mb-4 leading-relaxed">
                  Each fortune cookie comes with a meaningful message and your
                  personal lucky numbers. Choose from themes like inspirational,
                  funny, love, career, and wisdom to get fortunes that match
                  your mood.
                </p>
                <div className="flex flex-wrap gap-3 mt-6">
                  <a
                    href="/generator"
                    className="inline-flex items-center px-4 py-2 rounded-full bg-amber-100 text-amber-800 text-sm font-medium hover:bg-amber-200 transition-colors"
                  >
                    AI Generator
                  </a>
                  <a
                    href="/explore"
                    className="inline-flex items-center px-4 py-2 rounded-full bg-indigo-100 text-indigo-800 text-sm font-medium hover:bg-indigo-200 transition-colors"
                  >
                    Browse 500+ Fortunes
                  </a>
                </div>
              </div>
              <div>
                <h2 className="text-2xl font-heading font-semibold text-slate-800 mb-4">
                  How It Works
                </h2>
                <ol className="space-y-4">
                  <li className="flex gap-3">
                    <span className="flex-shrink-0 w-8 h-8 rounded-full bg-amber-500 text-white flex items-center justify-center text-sm font-bold">
                      1
                    </span>
                    <div>
                      <p className="font-medium text-slate-800">
                        Click the Cookie
                      </p>
                      <p className="text-sm text-slate-600">
                        Tap or click on the fortune cookie to crack it open.
                      </p>
                    </div>
                  </li>
                  <li className="flex gap-3">
                    <span className="flex-shrink-0 w-8 h-8 rounded-full bg-amber-500 text-white flex items-center justify-center text-sm font-bold">
                      2
                    </span>
                    <div>
                      <p className="font-medium text-slate-800">
                        Read Your Fortune
                      </p>
                      <p className="text-sm text-slate-600">
                        Discover your unique AI-generated fortune message.
                      </p>
                    </div>
                  </li>
                  <li className="flex gap-3">
                    <span className="flex-shrink-0 w-8 h-8 rounded-full bg-amber-500 text-white flex items-center justify-center text-sm font-bold">
                      3
                    </span>
                    <div>
                      <p className="font-medium text-slate-800">
                        Share & Enjoy
                      </p>
                      <p className="text-sm text-slate-600">
                        Share your fortune with friends or save your lucky
                        numbers!
                      </p>
                    </div>
                  </li>
                </ol>
                <div className="mt-6 p-4 rounded-xl bg-amber-50 border border-amber-200/50">
                  <p className="text-sm text-amber-800">
                    <strong>Tip:</strong> Want more personalized fortunes? Try
                    our{" "}
                    <a
                      href="/generator"
                      className="text-amber-700 underline hover:text-amber-900"
                    >
                      AI Fortune Cookie Generator
                    </a>{" "}
                    with 6 unique themes!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="relative z-10 py-16 bg-white/80 backdrop-blur-sm border-t border-amber-100/50">
          <div className="container mx-auto px-4 max-w-3xl">
            <h2 className="text-2xl md:text-3xl font-heading font-bold text-center text-slate-800 mb-10">
              Frequently Asked Questions
            </h2>
            <div className="space-y-6">
              {faqs.map((faq) => (
                <div
                  key={faq.question}
                  className="p-5 rounded-xl bg-white border border-slate-100 shadow-sm"
                >
                  <h3 className="font-semibold text-slate-800 mb-2">
                    {faq.question}
                  </h3>
                  <p className="text-slate-600 text-sm leading-relaxed">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Internal Links Section */}
        <section className="relative z-10 py-12 bg-gradient-to-b from-white to-amber-50/30">
          <div className="container mx-auto px-4 text-center">
            <h2 className="text-xl font-heading font-semibold text-slate-800 mb-6">
              Explore More Fortune Cookie Fun
            </h2>
            <div className="flex flex-wrap justify-center gap-4">
              <a
                href="/funny-fortune-cookie-messages"
                className="px-5 py-2.5 rounded-full bg-white border border-slate-200 text-slate-700 text-sm font-medium hover:border-amber-300 hover:bg-amber-50 transition-colors"
              >
                Funny Messages
              </a>
              <a
                href="/how-to-make-fortune-cookies"
                className="px-5 py-2.5 rounded-full bg-white border border-slate-200 text-slate-700 text-sm font-medium hover:border-amber-300 hover:bg-amber-50 transition-colors"
              >
                Make Your Own Cookies
              </a>
              <a
                href="/who-invented-fortune-cookies"
                className="px-5 py-2.5 rounded-full bg-white border border-slate-200 text-slate-700 text-sm font-medium hover:border-amber-300 hover:bg-amber-50 transition-colors"
              >
                History of Fortune Cookies
              </a>
              <a
                href="/blog"
                className="px-5 py-2.5 rounded-full bg-white border border-slate-200 text-slate-700 text-sm font-medium hover:border-amber-300 hover:bg-amber-50 transition-colors"
              >
                Fortune Cookie Blog
              </a>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
