import { Metadata } from "next";
import { DynamicBackgroundEffects } from "@/components/DynamicBackgroundEffects";
import { BreadcrumbStructuredData } from "@/components/StructuredData";
import { FAQStructuredData } from "@/components/FAQStructuredData";
import { getImageUrl, getSiteUrl } from "@/lib/site";
import { generateAlternateLanguages } from "@/lib/i18n-config";
import { GeneratorClient } from "./GeneratorClient";
import { AdUnit } from "@/components/AdUnit";

const baseUrl = getSiteUrl();

// ISR: force-static + revalidate every 24 hours
// The generator page shell is static (metadata, layout, FAQ schema).
// All interactive AI generation happens client-side via GeneratorClient.
// Caching the shell eliminates unnecessary SSR on every visit.
export const dynamic = "force-static";
export const revalidate = 86400; // 24 hours

export const metadata: Metadata = {
  title: "Fortune Cookie Generator — Free AI-Powered, Instant & Personalized",
  description:
    "Generate a free AI fortune cookie in seconds. Choose from 6 themes (Inspirational, Funny, Love, Wisdom, Success, Mystical), get lucky numbers, and share instantly. No signup needed — 5 free fortunes per day.",
  keywords: [
    "fortune cookie generator",
    "AI fortune cookie generator",
    "free fortune cookie generator",
    "online fortune cookie",
    "fortune cookie online free",
    "random fortune cookie",
    "fortune cookie maker",
    "personalized fortune cookie",
  ],
  openGraph: {
    title: "Fortune Cookie Generator — Free AI-Powered, Instant & Personalized",
    description:
      "Generate a free AI fortune cookie in seconds. Choose from 6 themes, get lucky numbers, and share instantly. No signup needed.",
    type: "website",
    url: `${baseUrl}/generator`,
    images: [
      {
        url: getImageUrl("/og-image.png"),
        width: 1200,
        height: 630,
        alt: "Free AI Fortune Cookie Generator",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Fortune Cookie Generator — Free AI-Powered, Instant & Personalized",
    description:
      "Generate a free AI fortune cookie in seconds. Choose from 6 themes, get lucky numbers, and share instantly. No signup needed.",
    images: [getImageUrl("/twitter-image.png")],
    creator: "@fortunecookieai",
  },
  alternates: {
    canonical: "/generator",
    languages: generateAlternateLanguages("/generator", baseUrl),
  },
};

export default function GeneratorPage() {
  return (
    <>
      <BreadcrumbStructuredData
        items={[
          { name: "Home", url: "/" },
          { name: "Fortune Cookie Generator", url: "/generator" },
        ]}
      />
      <FAQStructuredData
        faqs={[
          {
            question: "How do I use the AI fortune cookie generator?",
            answer:
              "Simply choose a theme (like Inspirational, Funny, or Love), select your mood, and click the fortune cookie to crack it open. Our AI will generate a unique personalized fortune message with lucky numbers instantly. No account or signup is required.",
          },
          {
            question: "How many fortune cookies can I generate for free?",
            answer:
              "Guest users can generate up to 5 free AI fortune cookies per day. Sign in with Google to unlock 20 daily fortunes — completely free, no payment required!",
          },
          {
            question: "Can I customize my fortune cookie message?",
            answer:
              "Yes! You can select from 6 different themes (Inspirational, Funny, Love, Wisdom, Success, Mystical) and various moods to personalize your fortune. Each combination produces a unique AI-generated message tailored to your preferences.",
          },
          {
            question: "Are the fortune cookie messages generated by real AI?",
            answer:
              "Yes, our fortune messages are generated by advanced AI models in real-time. Each fortune is unique and created specifically for you based on your chosen theme and mood. We also maintain a 500+ message offline library as a backup.",
          },
          {
            question: "Is this fortune cookie generator really free?",
            answer:
              "Yes, completely free. Guest users get 5 AI fortunes per day. Sign in with Google for 20 daily fortunes. No credit card, no subscription, no hidden fees.",
          },
          {
            question: "Can I use the generated fortunes for my business or event?",
            answer:
              "Absolutely. The fortunes are suitable for personal and commercial use. Many users print them for wedding favors, corporate events, restaurant menus, and branded gift packaging.",
          },
          {
            question: "What languages does the fortune cookie generator support?",
            answer:
              "The generator supports English, Spanish, French, German, Chinese (Simplified), Japanese, and several other languages. Select your preferred language in the Personalization panel before generating.",
          },
          {
            question: "How do the lucky numbers work?",
            answer:
              "Each fortune comes with a set of AI-selected lucky numbers generated algorithmically. They are meant purely for fun — think of them as your personal lottery picks or a playful nod to the tradition of fortune cookie lucky numbers.",
          },
        ]}
      />
      <main className="min-h-screen w-full overflow-x-hidden relative">
        <DynamicBackgroundEffects />
        <div className="relative z-10">
          <GeneratorClient />
          <div className="py-4 flex justify-center">
            <AdUnit slot="8173598207" />
          </div>
        </div>
      </main>
    </>
  );
}
