import { Metadata } from "next";
import { DynamicBackgroundEffects } from "@/components/DynamicBackgroundEffects";
import { BreadcrumbStructuredData } from "@/components/StructuredData";
import { FAQStructuredData } from "@/components/FAQStructuredData";
import { getImageUrl, getSiteUrl } from "@/lib/site";
import { generateAlternateLanguages } from "@/lib/i18n-config";
import { GeneratorClient } from "./GeneratorClient";

const baseUrl = getSiteUrl();

export const metadata: Metadata = {
  title: "Free Fortune Cookie Generator - AI Powered | Get Your Fortune Now",
  description:
    "Open your free AI fortune cookie now! Get personalized fortune messages, lucky numbers & life wisdom. 500+ unique fortunes - no signup needed. Try it instantly!",
  openGraph: {
    title: "Free Fortune Cookie Generator - AI Powered | Get Your Fortune Now",
    description:
      "Open your free AI fortune cookie now! Get personalized fortune messages, lucky numbers & life wisdom. 500+ unique fortunes - no signup needed.",
    type: "website",
    url: `${baseUrl}/generator`,
    images: [
      {
        url: getImageUrl("/og-image.png"),
        width: 1200,
        height: 630,
        alt: "Free AI Fortune Cookie Generator",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Free Fortune Cookie Generator - AI Powered | Get Your Fortune Now",
    description:
      "Open your free AI fortune cookie now! Get personalized fortune messages, lucky numbers & life wisdom. 500+ unique fortunes - no signup needed.",
    images: [getImageUrl("/twitter-image.png")],
    creator: "@fortunecookieai",
  },
  alternates: {
    canonical: "/generator",
    languages: generateAlternateLanguages("/generator", baseUrl),
  },
};

export default function GeneratorPage() {
  return (
    <>
      <BreadcrumbStructuredData
        items={[
          { name: "Home", url: "/" },
          { name: "Generator", url: "/generator" },
        ]}
      />
      <FAQStructuredData
        faqs={[
          {
            question: "How do I use the AI fortune cookie generator?",
            answer:
              "Simply choose a theme (like Inspirational, Funny, or Love), select your mood, and click the fortune cookie to crack it open. Our AI will generate a unique personalized fortune message with lucky numbers instantly.",
          },
          {
            question: "How many fortune cookies can I generate for free?",
            answer:
              "Guest users can generate up to 5 free AI fortune cookies per day. Sign in with Google to unlock 20 daily fortunes — completely free, no payment required!",
          },
          {
            question: "Can I customize my fortune cookie message?",
            answer:
              "Yes! You can select from 6 different themes and various moods to personalize your fortune. Each combination produces a unique AI-generated message tailored to your preferences.",
          },
          {
            question:
              "Are the fortune cookie messages generated by real AI?",
            answer:
              "Yes, our fortune messages are generated by advanced AI models in real-time. Each fortune is unique and created specifically for you based on your chosen theme and mood.",
          },
        ]}
      />
      <main className="min-h-screen w-full overflow-x-hidden relative">
        <DynamicBackgroundEffects />
        <div className="relative z-10">
          <GeneratorClient />
        </div>
      </main>
    </>
  );
}
