/**
 * Auto-generated Vercel Blob Storage URLs
 * Generated by: scripts/upload-to-blob.js
 * Generated at: 2025-11-30T10:07:42.736Z
 * 
 * DO NOT EDIT MANUALLY - Re-run the upload script to regenerate
 */

// Blob store base URL (extracted from first URL)
export const BLOB_STORE_BASE_URL = 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com';

// Individual blob URLs mapped from original paths
export const BLOB_URLS: Record<string, string> = {
  '/android-chrome-192x192.png': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/android-chrome-192x192.png',
  '/android-chrome-192x192.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/android-chrome-192x192.svg',
  '/android-chrome-512x512.png': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/android-chrome-512x512.png',
  '/android-chrome-512x512.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/android-chrome-512x512.svg',
  '/apple-touch-icon.png': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/apple-touch-icon.png',
  '/apple-touch-icon.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/apple-touch-icon.svg',
  '/favicon-16x16.png': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/favicon-16x16.png',
  '/favicon-16x16.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/favicon-16x16.svg',
  '/favicon-32x32.png': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/favicon-32x32.png',
  '/favicon-32x32.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/favicon-32x32.svg',
  '/favicon.ico': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/favicon.ico',
  '/icon.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/icon.svg',
  '/images/blog/ai-fortune-telling-hero.jpg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/images/blog/ai-fortune-telling-hero.jpg',
  '/images/blog/fortune-cookies-origins-hero.jpg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/images/blog/fortune-cookies-origins-hero.jpg',
  '/images/blog/history-fortune-cookies-hero.jpg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/images/blog/history-fortune-cookies-hero.jpg',
  '/images/blog/psychology-fortune-cookies-hero.jpg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/images/blog/psychology-fortune-cookies-hero.jpg',
  '/images/blog/psychology-luck-hero.jpg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/images/blog/psychology-luck-hero.jpg',
  '/images/fortune-cookie-banner.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/images/fortune-cookie-banner.svg',
  '/images/fortune-cookie-hero.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/images/fortune-cookie-hero.svg',
  '/logo.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/logo.svg',
  '/og-image.png': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/og-image.png',
  '/og-image.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/og-image.svg',
  '/twitter-image.png': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/twitter-image.png',
  '/twitter-image.svg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/twitter-image.svg',
};

// Helper function to get blob URL for an image path
export function getBlobUrl(imagePath: string): string {
  // Normalize path to start with /
  const normalizedPath = imagePath.startsWith('/') ? imagePath : `/${imagePath}`;
  return BLOB_URLS[normalizedPath] || imagePath;
}

// Check if an image path has a blob URL
export function hasBlobUrl(imagePath: string): boolean {
  const normalizedPath = imagePath.startsWith('/') ? imagePath : `/${imagePath}`;
  return normalizedPath in BLOB_URLS;
}
