/**
 * Auto-generated Vercel Blob Storage URLs
 * Generated by: scripts/upload-to-blob.js
 * Generated at: 2025-12-10T10:17:58.017Z
 * 
 * DO NOT EDIT MANUALLY - Re-run the upload script to regenerate
 */

// Blob store base URL (extracted from first URL)
export const BLOB_STORE_BASE_URL = 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com';

// Individual blob URLs mapped from original paths
export const BLOB_URLS: Record<string, string> = {
  '/images/blog/funny-fortune-cookie-hero.jpg': 'https://oxnbbm6ljoyuzqns.public.blob.vercel-storage.com/images/blog/funny-fortune-cookie-hero.jpg',
};

// Helper function to get blob URL for an image path
export function getBlobUrl(imagePath: string): string {
  // Normalize path to start with /
  const normalizedPath = imagePath.startsWith('/') ? imagePath : `/${imagePath}`;
  return BLOB_URLS[normalizedPath] || imagePath;
}

// Check if an image path has a blob URL
export function hasBlobUrl(imagePath: string): boolean {
  const normalizedPath = imagePath.startsWith('/') ? imagePath : `/${imagePath}`;
  return normalizedPath in BLOB_URLS;
}
